//Department
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";

//Employee
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";

//Theme
